spring.application.name=bookstore

# SQLite接続設定                                                                                                                                                                              
spring.datasource.url=jdbc:sqlite:bookstore.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA設定
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# ロケール設定
spring.web.locale=ja_JP
spring.web.locale-resolver=fixed

# Thymeleaf設定
spring.thymeleaf.cache=false